-- DEPRECATED — DO NOT RUN
--
-- Project Hub finalization for Koshora App #2 is now included atomically in:
-- database/koshora__001_core_finance_backend.sql
--
-- This file is intentionally retained as a safe stub so stale references cannot
-- apply the old split-finalization workflow.
