-- DEPRECATED — DO NOT RUN
--
-- Koshora now follows Project Hub Architecture v2.
-- The authoritative registration migration is:
--
--   database/koshora__000_register_app.sql
--
-- That migration requires the repository safety contract, verifies Hub
-- architecture v2, registers Koshora as App #2, runs hub.assert_app_scope(),
-- and creates only the empty deny-by-default koshora schema.
--
-- This file is intentionally retained only to prevent stale documentation or
-- old links from silently executing the former pre-v2 onboarding flow.
