-- DEPRECATED — DO NOT RUN
--
-- Koshora now uses Project Hub Architecture v2 migrations.
-- Registration: database/koshora__000_register_app.sql
-- Core backend: database/koshora__001_core_finance_backend.sql
--
-- This file is intentionally retained only to prevent stale links from silently
-- running an outdated migration workflow.
