"use client";

import { useState } from "react";
import { formatINR, toCsv, type Account } from "@/lib/finance";
import { download, PanelHead } from "@/components/finance-primitives";

export function Accounts({ data, onCreate, onDelete }: any) {
  const [name,setName]=useState("");const [type,setType]=useState<Account["type"]>("bank");const [balance,setBalance]=useState("0");
  return <div className="view-stack"><section className="intro-card"><div><span className="eyebrow">Money containers</span><h2>See where your balance actually lives.</h2><p>Cash, bank, wallet, card and savings accounts stay separated.</p></div><div className="inline-form"><input placeholder="Account name" value={name} onChange={(e)=>setName(e.target.value)}/><select value={type} onChange={(e)=>setType(e.target.value)}><option value="bank">Bank</option><option value="cash">Cash</option><option value="wallet">Wallet</option><option value="credit">Credit card</option><option value="savings">Savings</option></select><input type="number" value={balance} onChange={(e)=>setBalance(e.target.value)} aria-label="Opening balance"/><button className="primary" onClick={()=>{if(name.trim()){onCreate(name.trim(),type,Number(balance)||0);setName("");setBalance("0");}}}>Add account</button></div></section><section className="account-grid">{data.accounts.map((a:Account)=><article className="account-card" key={a.id}><div className="account-icon">{a.type.slice(0,2).toUpperCase()}</div><span>{a.type}</span><h3>{a.name}</h3><strong>{formatINR(a.balance)}</strong><button className="ghost danger" onClick={()=>onDelete(a)}>Remove</button></article>)}</section></div>;
}

export function Settings({ mode, theme, setTheme, data, reset }: any) {
  return <div className="settings-grid"><section className="panel"><PanelHead title="Appearance" detail="Designed intentionally in light and dark"/><div className="segmented">{["light","dark","system"].map((t)=><button key={t} className={theme===t?"active":""} onClick={()=>setTheme(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div></section><section className="panel"><PanelHead title="Data portability" detail="Your data should never feel trapped"/><div className="setting-actions"><button className="secondary" onClick={()=>download("koshora-transactions.csv",toCsv(data),"text/csv")}>Export CSV</button><button className="secondary" onClick={()=>download("koshora-backup.json",JSON.stringify(data,null,2),"application/json")}>Export JSON</button>{mode==="demo"&&<button className="secondary danger" onClick={reset}>Reset demo</button>}</div></section><section className="panel"><PanelHead title="Privacy model" detail={mode==="demo"?"Browser-only demo":"Supabase-backed private workspace"}/><p className="setting-copy">{mode==="demo"?"Recruiter demo data is stored only in localStorage on this browser. No financial credentials are requested or transmitted.":"Cloud mode uses authenticated Supabase access and user-scoped Row Level Security policies so each account can access only its own rows."}</p></section></div>;
}
